#!/bin/bash

script_dir=$(dirname "$0")
set -ex
cd ${script_dir}
rm -rf ./dist
/usr/bin/python3 -m pip install build --break-system-packages
/usr/bin/python3 -m build
/usr/bin/python3 -m pip install -e . --break-system-packages
