# RECIPE
# Build the AppImage anywhere you have docker installed and the resources.
#
#    docker pull appimagecrafters/appimage-builder:latest
#    docker run --name appimage -it appimagecrafters/appimage-builder /bin/bash # 1st time
#    docker exec -it appimage bash # get another shell (then 'cd')
#    docker start -i appimage # re-enter after it has exited
#    
#  Some Basic Tool Setup (inside the container)
# 
#   apt update
#   apt install vim git
#   vim ~/.vimrc # and add... (to keep consistent if editing)
#       syntax on
#       set tabstop=4
#       set shiftwidth=4
#       set softtabstop=4
#       set expandtab
#       set autoindent 
#   alias ls="/bin/ls --color=never -p" # if you wish
#
# Build the AppImage (inside the container)
#
#   git clone https://github.com/joedefen/pwr-tray.git
#   ln -s pwr-tray/recipe.yaml recipe.yaml   # For convenience
#   vim recipe.yaml  # optionally, modify recipe
#   appimage-builder --recipe recipe.yaml
#   
# Copy the AppImage to Your Host (outside the container)
#
#    - Inside the docker container, check the AppImage name and replace the AppImage file
#      name in the following commands as required.
#    - On your docker host:
#      docker cp appimage:/root/deluge-0.0-x86_64.AppImage ./pwr-tray && chmod +x pwr-tray

version: 1

script: []

AppDir:
  path: ./AppDir

  app_info:
    id: deluged
    name: deluged
    icon: utilities-terminal
    version: 0.0
    exec: usr/bin/python3
    exec_args: "$APPDIR/src/pwr_tray/main.py $@"

  apt:
    arch: amd64
    sources: # focal is 20.04
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse'
        key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C'
    
    include:
      - python3
      - python3-pkg-resources
      - python3-pyqt5
      - gnome-themes-standard
      - adwaita-icon-theme
      - breeze-icon-theme
      - hicolor-icon-theme
      - gnome-icon-theme
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      # - gir1.2-appindicator3
      - gir1.2-appindicator3-0.1
      - libappindicator3-1
      - perl
      - bash
      - dash
      - coreutils
      - playerctl
      - xset
      - xprintidle
      - swaymsg
      - i3lock
      - i3-msg
      - loginctl
      - qdbus

    exclude: []

  runtime:
    env:
     PATH: $APPDIR/usr/bin:$PATH
     APPDIR_LIBRARY_PATH: $APPDIR/usr/lib/x86_64-linux-gnu/
     PYTHONHOME: $APPDIR/usr
     PYTHONPATH: $APPDIR/usr/lib/python3/dist-packages

  files:
    exclude:
      - usr/lib/x86_64-linux-gnu/gconv
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*

AppImage:
  update-information: None
  sign-key: None
  arch: x86_64