#!/usr/bin/env python3
"""
runner - Development wrapper for app
Located in the top-level app directory.
Allows running app from source for debugging with support for command-line arguments.

Usage:
    ./runner {options-and-args}
    ./runner --help     (show all available options)
"""

import runpy
import sys

if __name__ == '__main__':
    # Set program name but preserve all command-line arguments
    sys.argv[0] = 'pwr-tray'
    # Run the dwipe.main module with alter_sys=True to propagate sys.argv
    runpy.run_module('pwr_tray.main', run_name='__main__', alter_sys=True)
